"use strict";
(() => {
  const SUPABASE_URL="https://ethlgaszdextwckdwgsf.supabase.co";
  const SUPABASE_KEY="sb_publishable_qEhxWcCbekPjYFUW-EQ1ow_xccHG8aJ";
  const $=(s,r=document)=>r.querySelector(s);
  const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
  const dt=v=>v?new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"—";
  let db,storeId=0,customers=[],summary={},config={},campaigns=[],points=new Map();
  function notify(msg,type="success"){if(typeof window.GoBurgerUI?.toast==="function")return window.GoBurgerUI.toast(msg,type);const n=document.createElement("div");n.textContent=msg;n.style.cssText="position:fixed;right:20px;bottom:20px;z-index:99999;background:#1f1713;color:#fff;padding:12px 16px;border-radius:12px";document.body.append(n);setTimeout(()=>n.remove(),3500)}
  function inject(){const page=$('[data-section="clientes"]');if(!page||$("#gbCrmKpis"))return;const toolbar=page.querySelector(".page-toolbar");toolbar?.insertAdjacentHTML("beforeend",'<button class="btn primary" id="gbNewCrmCampaign" type="button"><i class="fa-solid fa-paper-plane"></i> Nova campanha CRM</button>');const panel=page.querySelector("article.panel");panel?.insertAdjacentHTML("beforebegin",`<div class="gb-growth-grid" id="gbCrmKpis"></div>`);panel?.insertAdjacentHTML("afterend",`<div class="gb-growth-layout"><article class="gb-growth-panel"><h3>Automações de retenção</h3><p>Regras automáticas para recorrência, VIP, inatividade e aniversário.</p><form id="gbCrmConfigForm" class="gb-growth-form"><label>Recorrente a partir de<input name="recorrente_min_pedidos" type="number" min="2"></label><label>VIP a partir de pedidos<input name="vip_min_pedidos" type="number" min="2"></label><label>VIP por gasto mínimo<input name="vip_min_gasto" type="number" min="0" step="0.01"></label><label>Inativo após (dias)<input name="inativo_dias" type="number" min="7"></label><label class="gb-growth-check"><input name="automacao_inativos_ativa" type="checkbox"> Reativar inativos automaticamente</label><label>Desconto inativo (%)<input name="inativos_desconto_percentual" type="number" min="0" max="100" step="0.01"></label><label>Dias do cupom de retorno<input name="inativos_cupom_dias" type="number" min="1"></label><label class="gb-growth-check"><input name="automacao_aniversario_ativa" type="checkbox"> Cupom de aniversário automático</label><label>Desconto aniversário (%)<input name="aniversario_desconto_percentual" type="number" min="0" max="100" step="0.01"></label><label>Dias do cupom de aniversário<input name="aniversario_cupom_dias" type="number" min="1"></label><div class="wide gb-growth-actions"><button class="gb-growth-btn" type="submit">Salvar automações</button></div></form></article><article class="gb-growth-panel"><h3>Campanhas da hamburgueria</h3><p>In-app, Push e WhatsApp conforme consentimento de cada cliente.</p><div id="gbCrmCampaignList" class="gb-growth-list"></div></article></div>`);
    document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="gbCrmCampaignModal"><div class="modal-card"><button class="modal-close" id="gbCrmClose" type="button"><i class="fa-solid fa-xmark"></i></button><div class="modal-head"><span class="eyebrow">CRM AUTOMATION</span><h2>Nova campanha</h2></div><form id="gbCrmCampaignForm" class="gb-growth-form"><label class="wide">Nome<input name="nome" required placeholder="Ex.: Volta pro burger"></label><label>Objetivo<select name="objetivo"><option value="marketing">Marketing</option><option value="retencao">Retenção</option><option value="reativacao">Reativação</option><option value="aniversario">Aniversário</option><option value="fidelizacao">Fidelização</option><option value="informativo">Informativo</option></select></label><label>Segmento<select name="segmento"><option value="todos">Todos</option><option value="novo">Novos</option><option value="recorrente">Recorrentes</option><option value="vip">VIP</option><option value="inativo">Inativos</option><option value="aniversariante">Aniversariantes</option></select></label><label class="wide">Canais<div class="gb-growth-actions"><label class="gb-growth-check"><input name="in_app" type="checkbox" checked> In-app</label><label class="gb-growth-check"><input name="push" type="checkbox"> Push</label><label class="gb-growth-check"><input name="whatsapp" type="checkbox"> WhatsApp</label></div></label><label class="wide">Título<input name="titulo" required></label><label class="wide">Mensagem<textarea name="mensagem" rows="4" required></textarea></label><label>Agendar<input name="agendada_para" type="datetime-local"></label><label>Template WhatsApp<input name="whatsapp_template" placeholder="nome_template_aprovado"></label><label>Idioma WhatsApp<input name="whatsapp_language" value="pt_BR"></label><div class="wide gb-growth-actions"><button class="gb-growth-btn" type="submit">Criar e preparar campanha</button></div></form></div></div>`);
    bind();
  }
  async function context(){storeId=Number($("#adminLojaSelect")?.value||localStorage.getItem("go_burger_admin_loja_id")||0);return storeId}
  async function load(){if(!db||!await context())return;try{const [c,s,consoleData,ms]=await Promise.all([db.rpc("go_burger_clientes_segmentados_v1",{p_loja_id:storeId}),db.rpc("go_burger_crm_resumo_v1",{p_loja_id:storeId}),db.rpc("go_burger_crm_console_v611",{p_loja_id:storeId}),db.rpc("go_burger_mensageria_resumo_v1",{p_loja_id:storeId})]);for(const r of [c,s,consoleData,ms])if(r.error)throw r.error;customers=c.data||[];summary=s.data||{};config=consoleData.data?.config||{};campaigns=consoleData.data?.campaigns||[];points=new Map();(consoleData.data?.points||[]).forEach(x=>points.set(x.user_id,Number(x.pontos||0)));summary.mensageria=ms.data||{};render();}catch(e){console.warn("Go-burger CRM",e);notify(e.message||"Não foi possível carregar o CRM.","error")}}
  function render(){const k=$("#gbCrmKpis");if(k)k.innerHTML=[['Clientes',summary.total||customers.length,'base da loja'],['Novos',summary.novos||0,'primeiro ciclo'],['Recorrentes',summary.recorrentes||0,'voltaram a comprar'],['VIP',summary.vip||0,'alto valor'],['Inativos',summary.inativos||0,`≥ ${config.inativo_dias||45} dias`],['Aniversariantes',summary.aniversariantes||0,'hoje'],['Push',summary.aceitam_push||0,'opt-in'],['WhatsApp',summary.aceitam_whatsapp||0,'opt-in']].map(x=>`<article class="gb-growth-card"><small>${x[0]}</small><strong>${x[1]}</strong><p>${x[2]}</p></article>`).join("");renderTable();renderConfig();renderCampaigns()}
  function renderTable(){const body=$("#tabelaClientes");if(!body)return;const q=String($("#pesquisaCliente")?.value||"").toLowerCase(),seg=$("#filtroSegmentoCliente")?.value||"";const list=customers.filter(c=>(!q||`${c.nome||""} ${c.email||""} ${c.telefone||""}`.toLowerCase().includes(q))&&(!seg||c.segmento===seg));$("#contadorClientes").textContent=`${list.length} cliente(s)`;body.innerHTML=list.length?list.map(c=>`<tr><td><div class="client-cell"><span class="client-avatar">${esc((c.nome||"C").slice(0,1).toUpperCase())}</span><div><strong>${esc(c.nome||"Cliente")}${c.aniversariante?' 🎂':''}</strong><small>${esc(c.email||"—")} · ${esc(c.telefone||"—")}</small></div></div></td><td><span class="segment ${esc(c.segmento)}">${esc(c.segmento||"novo")}</span></td><td>${Number(c.pedidos_total||0)}</td><td><strong>${money(c.total_gasto)}</strong></td><td>${money(c.ticket_medio)}</td><td><strong>${points.get(c.id)||0}</strong></td><td>${dt(c.ultimo_pedido)}</td><td><button class="action-btn" data-client-details="${c.id}" title="Ver cliente"><i class="fa-solid fa-eye"></i></button></td></tr>`).join(""):`<tr><td colspan="8">Nenhum cliente neste segmento.</td></tr>`}
  function renderConfig(){const f=$("#gbCrmConfigForm");if(!f)return;["recorrente_min_pedidos","vip_min_pedidos","vip_min_gasto","inativo_dias","inativos_desconto_percentual","inativos_cupom_dias","aniversario_desconto_percentual","aniversario_cupom_dias"].forEach(n=>{if(f.elements[n])f.elements[n].value=config[n]??""});["automacao_inativos_ativa","automacao_aniversario_ativa"].forEach(n=>{if(f.elements[n])f.elements[n].checked=!!config[n]})}
  function renderCampaigns(){const w=$("#gbCrmCampaignList");if(!w)return;w.innerHTML=campaigns.length?campaigns.map(c=>`<article class="gb-growth-item"><div><strong>${esc(c.nome)}</strong><small>${esc(c.segmento)} · ${(c.canais||[]).join(" + ")} · ${dt(c.agendada_para||c.criado_em)}</small></div><span class="gb-chip">${esc(c.status)}</span></article>`).join(""):'<p>Nenhuma campanha CRM criada.</p>'}
  function openModal(){const m=$("#gbCrmCampaignModal");m?.classList.add("active")}
  function closeModal(){$("#gbCrmCampaignModal")?.classList.remove("active")}
  async function saveConfig(e){e.preventDefault();const f=e.currentTarget;const r=await db.rpc("go_burger_crm_config_salvar_v611",{p_loja_id:storeId,p_recorrente_min_pedidos:Number(f.elements.recorrente_min_pedidos.value||2),p_vip_min_pedidos:Number(f.elements.vip_min_pedidos.value||5),p_vip_min_gasto:Number(f.elements.vip_min_gasto.value||300),p_inativo_dias:Number(f.elements.inativo_dias.value||45),p_automacao_inativos_ativa:f.elements.automacao_inativos_ativa.checked,p_inativos_desconto_percentual:Number(f.elements.inativos_desconto_percentual.value||12),p_inativos_cupom_dias:Number(f.elements.inativos_cupom_dias.value||7),p_automacao_aniversario_ativa:f.elements.automacao_aniversario_ativa.checked,p_aniversario_desconto_percentual:Number(f.elements.aniversario_desconto_percentual.value||15),p_aniversario_cupom_dias:Number(f.elements.aniversario_cupom_dias.value||7)});if(r.error)return notify(r.error.message,"error");notify("Automações do CRM atualizadas.");await load()}
  async function saveCampaign(e){e.preventDefault();const f=e.currentTarget;const channels=[f.elements.in_app.checked&&"in_app",f.elements.push.checked&&"push",f.elements.whatsapp.checked&&"whatsapp"].filter(Boolean);if(!channels.length)return notify("Selecione ao menos um canal.","error");const scheduled=f.elements.agendada_para.value?new Date(f.elements.agendada_para.value).toISOString():null;const r=await db.rpc("go_burger_crm_campanha_criar_v611",{p_loja_id:storeId,p_nome:f.elements.nome.value.trim(),p_objetivo:f.elements.objetivo.value,p_segmento:f.elements.segmento.value,p_canais:channels,p_titulo:f.elements.titulo.value.trim(),p_mensagem:f.elements.mensagem.value.trim(),p_agendada_para:scheduled,p_whatsapp_template:f.elements.whatsapp_template.value.trim()||null,p_whatsapp_language:f.elements.whatsapp_language.value.trim()||"pt_BR"});if(r.error)return notify(r.error.message,"error");notify(scheduled?"Campanha agendada.":"Campanha preparada para envio.");f.reset();f.elements.in_app.checked=true;closeModal();await load()}
  function bind(){$("#gbNewCrmCampaign")?.addEventListener("click",openModal);$("#gbCrmClose")?.addEventListener("click",closeModal);$("#gbCrmConfigForm")?.addEventListener("submit",saveConfig);$("#gbCrmCampaignForm")?.addEventListener("submit",saveCampaign);$("#pesquisaCliente")?.addEventListener("input",renderTable);$("#filtroSegmentoCliente")?.addEventListener("change",renderTable);$("#adminLojaSelect")?.addEventListener("change",()=>setTimeout(load,700));$("#btnAtualizar")?.addEventListener("click",()=>setTimeout(load,900))}
  document.addEventListener("DOMContentLoaded",async()=>{if(!window.supabase?.createClient)return;db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,storageKey:"go-burger-auth-v1"}});inject();setTimeout(load,900)});
})();
