"use strict";
document.addEventListener("DOMContentLoaded",async()=>{
  const SUPABASE_URL="https://ethlgaszdextwckdwgsf.supabase.co",KEY="sb_publishable_qEhxWcCbekPjYFUW-EQ1ow_xccHG8aJ",BUCKET="go-burger-drivers";
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  let db=null;
  const state={user:null,application:null,invite:new URLSearchParams(location.search).get("convite")||"",uploading:false};let toastTimer=null;
  function toast(message,type="success"){const n=$("#driverSignupToast");if(!n)return;n.textContent=message;n.className=`driver-toast show ${type}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.className="driver-toast",3600)}
  function loading(btn,on,label="Processando..."){if(!btn)return;if(on){btn.dataset.old=btn.innerHTML;btn.disabled=true;btn.innerHTML=`<i class="fa-solid fa-spinner fa-spin"></i> ${esc(label)}`}else{btn.disabled=false;if(btn.dataset.old){btn.innerHTML=btn.dataset.old;delete btn.dataset.old}}}
  $$('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>switchAuth(b.dataset.authTab)));
  try{
    if(!window.supabase?.createClient)throw new Error("Serviço de autenticação indisponível. Verifique sua conexão e tente novamente.");
    db=window.supabase.createClient(SUPABASE_URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:"go-burger-auth-v1"}});
  }catch(e){console.error(e);toast(e.message||"Não foi possível iniciar o cadastro.","error");return}
  const statusCopy={pendente:["Cadastro enviado","Seus dados estão na fila de análise da Go-burger."],em_analise:["Cadastro em análise","Nossa equipe está conferindo os dados e documentos."],aguardando_correcao:["Precisamos de uma correção","Ajuste os pontos indicados e reenvie seu cadastro."],aprovada:["Perfil aprovado","Agora você pode aceitar vínculos com hamburguerias e ficar online."],rejeitada:["Cadastro não aprovado","Confira a observação da análise antes de reenviar."],suspensa:["Perfil suspenso","Seu acesso às entregas está temporariamente suspenso."]};
  function switchAuth(tab){$$('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===tab));$$('[data-auth-form]').forEach(f=>f.classList.toggle('active',f.dataset.authForm===tab))}
  function vehicleVisibility(){const motorized=["moto","carro"].includes($("#driverVehicleType")?.value);$$('.driver-cnh-fields').forEach(x=>x.classList.toggle('hidden',!motorized))}
  function safeName(name){return String(name||"arquivo").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]+/g,"-").slice(-90)}
  function formValue(name,value){const el=$(`[name="${name}"]`);if(el&&value!=null&&value!=="")el.value=value}
  function fillApplication(){const a=state.application||{};["nome","data_nascimento","telefone","email","endereco","cidade","estado","cep","contato_emergencia_nome","contato_emergencia_telefone","tipo_veiculo","modelo_veiculo","cor_veiculo","placa","cnh_categoria","cnh_validade","observacoes"].forEach(k=>formValue(k,a[k]));vehicleVisibility()}
  function renderDocs(){const docs=state.application?.documentos||[],w=$("#driverDocsList");if(!w)return;const labels={foto_perfil:"Foto de perfil",cnh_frente:"CNH · frente",cnh_verso:"CNH · verso",documento_veiculo:"Documento do veículo",comprovante_endereco:"Comprovante de endereço",outro:"Outro documento"};w.innerHTML=docs.length?docs.map(d=>`<article class="driver-doc-item"><i class="fa-solid ${d.mime_type==='application/pdf'?'fa-file-pdf':'fa-image'}"></i><div><strong>${esc(labels[d.tipo]||d.tipo)}</strong><small>${esc(d.nome_original||'Arquivo enviado')} · ${esc(d.status||'enviado')}</small></div><i class="fa-solid fa-circle-check"></i></article>`).join(""):'<article class="driver-doc-item"><i class="fa-solid fa-cloud-arrow-up"></i><div><strong>Nenhum documento enviado</strong><small>Comece pela foto de perfil.</small></div></article>'}
  function calculateProgress(){const f=$("#driverApplicationForm"),a=state.application||{},base=["nome","data_nascimento","telefone","cidade","estado","tipo_veiculo"],filled=base.filter(k=>String(f?.elements[k]?.value||a[k]||"").trim()).length;let score=Math.round((filled/base.length)*55);if(a.id)score+=15;const docs=a.documentos||[];if(docs.some(d=>d.tipo==='foto_perfil'))score+=15;if(!['moto','carro'].includes(f?.elements.tipo_veiculo?.value||a.tipo_veiculo)||docs.some(d=>d.tipo==='cnh_frente'))score+=15;score=Math.min(score,100);$("#driverProgressText").textContent=`${score}%`;$("#driverProgressBar").style.width=`${score}%`}
  function renderStatus(){const a=state.application,b=$("#driverStatusBanner");if(!b)return;const status=a?.status||"novo",copy=statusCopy[status]||["Comece seu cadastro","Preencha os dados abaixo e envie para análise."];b.dataset.status=status;$("#driverStatusTitle").textContent=copy[0];$("#driverStatusText").textContent=a?.observacao_analise?`${copy[1]} ${a.observacao_analise}`:copy[1];renderDocs();calculateProgress();$("#driverInviteCard")?.classList.toggle("hidden",!state.invite)}
  async function loadApplication(){const {data,error}=await db.rpc("go_burger_entregador_minha_solicitacao_v45");if(error)throw error;state.application=data||null;fillApplication();renderStatus()}
  async function sessionUI(){const {data,error}=await db.auth.getSession();if(error)throw error;state.user=data?.session?.user||null;document.body.classList.toggle("driver-has-session",!!state.user);$("#driverAuthCard").classList.toggle("hidden",!!state.user);$("#driverOnboarding").classList.toggle("hidden",!state.user);if(state.user){formValue("email",state.user.email||"");formValue("nome",state.user.user_metadata?.nome||"");formValue("telefone",state.user.user_metadata?.telefone||"");await loadApplication()}}
  async function signIn(form){const btn=form.querySelector('button[type="submit"]');loading(btn,true,"Entrando...");try{const {error}=await db.auth.signInWithPassword({email:form.elements.email.value.trim(),password:form.elements.password.value});if(error)throw error;toast("Login realizado.");await sessionUI()}catch(e){toast(e.message||"Não foi possível entrar.","error")}finally{loading(btn,false)}}
  async function signUp(form){const btn=form.querySelector('button[type="submit"]');loading(btn,true,"Criando conta...");try{const email=form.elements.email.value.trim(),password=form.elements.password.value,nome=form.elements.nome.value.trim(),telefone=form.elements.telefone.value.trim();const {data:signupGate,error:signupGateError}=await db.rpc("go_burger_plataforma_publica_v1");if(signupGateError)throw new Error("Não foi possível validar a abertura de novos cadastros. Tente novamente mais tarde.");if(signupGate?.manutencao||signupGate?.user_signups_enabled===false)throw new Error(signupGate?.manutencao_mensagem||"Novos cadastros estão temporariamente indisponíveis enquanto a Go Burger finaliza o lançamento.");const {data,error}=await db.auth.signUp({email,password,options:{data:{nome,telefone}}});if(error)throw error;if(!data.session){toast("Conta criada. Confirme o e-mail e depois entre.");switchAuth("login");$("#driverLoginForm").elements.email.value=email}else{toast("Conta criada. Complete seu cadastro.");await sessionUI()}}catch(e){toast(e.message||"Não foi possível criar a conta.","error")}finally{loading(btn,false)}}
  async function submitApplication(form){const btn=form.querySelector('button[type="submit"]');loading(btn,true,"Enviando...");try{const e=form.elements,birth=new Date(`${e.data_nascimento.value}T12:00:00`),age=(Date.now()-birth.getTime())/31557600000;if(!Number.isFinite(age)||age<18)throw new Error("O cadastro independente de entregador exige 18 anos ou mais.");const params={p_nome:e.nome.value.trim(),p_cpf:e.cpf.value.trim(),p_data_nascimento:e.data_nascimento.value,p_telefone:e.telefone.value.trim(),p_email:e.email.value.trim()||null,p_endereco:e.endereco.value.trim()||null,p_cidade:e.cidade.value.trim(),p_estado:e.estado.value.trim().toUpperCase(),p_cep:e.cep.value.trim()||null,p_contato_emergencia_nome:e.contato_emergencia_nome.value.trim()||null,p_contato_emergencia_telefone:e.contato_emergencia_telefone.value.trim()||null,p_tipo_veiculo:e.tipo_veiculo.value,p_modelo_veiculo:e.modelo_veiculo.value.trim()||null,p_cor_veiculo:e.cor_veiculo.value.trim()||null,p_placa:e.placa.value.trim().toUpperCase()||null,p_cnh_categoria:e.cnh_categoria.value.trim().toUpperCase()||null,p_cnh_validade:e.cnh_validade.value||null,p_observacoes:e.observacoes.value.trim()||null,p_aceite_termos:e.aceite_termos.checked,p_declaracao_veracidade:e.declaracao_veracidade.checked};const {data:launchGate,error:launchGateError}=await db.rpc("go_burger_plataforma_publica_v1");if(launchGateError)throw new Error("Não foi possível validar a abertura de novas solicitações. Tente novamente mais tarde.");if(launchGate?.manutencao||launchGate?.driver_applications_enabled===false)throw new Error(launchGate?.manutencao_mensagem||"Novas solicitações de entregadores estão temporariamente indisponíveis.");const {error}=await db.rpc("go_burger_entregador_enviar_solicitacao_v45",params);if(error)throw error;try{await db.rpc("go_burger_aceitar_termo_v1",{p_tipo:"entregador",p_versao:"1.2",p_aceito:true,p_origem:"cadastro_entregador"});await db.rpc("go_burger_aceitar_termo_v1",{p_tipo:"privacidade",p_versao:"1.2",p_aceito:true,p_origem:"cadastro_entregador"});}catch(termoError){console.warn("aceite jurídico entregador",termoError?.message||termoError)}toast("Cadastro enviado para análise.");await loadApplication();if(state.invite)await acceptInvite(true)}catch(err){toast(err.message||"Não foi possível enviar o cadastro.","error")}finally{loading(btn,false)}}
  async function uploadDocument(){if(state.uploading)return;const file=$("#driverDocFile").files?.[0],type=$("#driverDocType").value,btn=$("#driverUploadDoc");if(!state.application?.id)return toast("Salve o cadastro antes de enviar documentos.","error");if(!file)return toast("Selecione um arquivo.","error");if(file.size>10*1024*1024)return toast("O arquivo ultrapassa 10 MB.","error");if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(file.type))return toast("Formato de arquivo não permitido.","error");state.uploading=true;loading(btn,true,"Enviando...");try{const path=`${state.user.id}/${state.application.id}/${Date.now()}-${safeName(file.name)}`;const {error:upErr}=await db.storage.from(BUCKET).upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(upErr)throw upErr;const {error}=await db.rpc("go_burger_entregador_registrar_documento_v45",{p_tipo:type,p_storage_path:path,p_nome_original:file.name,p_mime:file.type,p_tamanho:file.size});if(error){await db.storage.from(BUCKET).remove([path]).catch(()=>{});throw error}$("#driverDocFile").value="";toast("Documento enviado com segurança.");await loadApplication()}catch(e){toast(e.message||"Falha no envio do documento.","error")}finally{state.uploading=false;loading(btn,false)}}
  async function acceptInvite(silent=false){if(!state.invite)return;const btn=$("#driverAcceptInvite");loading(btn,true,"Aceitando...");try{const {data,error}=await db.rpc("go_burger_entregador_aceitar_convite_v45",{p_token:state.invite});if(error)throw error;if(!silent)toast(data?.status==='vinculado'?"Convite aceito. Seu vínculo está ativo.":"Convite aceito. O vínculo será ativado após a aprovação do perfil.");if(data?.status==='vinculado')setTimeout(()=>location.href="entregador.html",800)}catch(e){if(!silent)toast(e.message||"Não foi possível aceitar o convite.","error")}finally{loading(btn,false)}}
  $("#driverLoginForm")?.addEventListener("submit",e=>{e.preventDefault();signIn(e.currentTarget)});$("#driverRegisterForm")?.addEventListener("submit",e=>{e.preventDefault();signUp(e.currentTarget)});$("#driverApplicationForm")?.addEventListener("submit",e=>{e.preventDefault();submitApplication(e.currentTarget)});$("#driverVehicleType")?.addEventListener("change",()=>{vehicleVisibility();calculateProgress()});$("#driverApplicationForm")?.addEventListener("input",calculateProgress);$("#driverUploadDoc")?.addEventListener("click",uploadDocument);$("#driverAcceptInvite")?.addEventListener("click",()=>acceptInvite(false));$("#driverLogout")?.addEventListener("click",async()=>{await db.auth.signOut();state.user=null;state.application=null;await sessionUI()});
  try{await sessionUI()}catch(e){console.error(e);toast(e.message||"Não foi possível abrir o cadastro.","error")}
});
