"use strict";
document.addEventListener("DOMContentLoaded",async()=>{
  const SUPABASE_URL="https://ethlgaszdextwckdwgsf.supabase.co",SUPABASE_PUBLISHABLE_KEY="sb_publishable_qEhxWcCbekPjYFUW-EQ1ow_xccHG8aJ";
  const $=s=>document.querySelector(s),html=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])),money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
  const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:"go-burger-auth-v1"}});
  const state={user:null,deliveries:[],activeDriverId:null,liveWatchId:null,available:false,application:null};let toastTimer=null;
  function toast(m){const e=$("#driverToast");if(!e)return;e.textContent=m;e.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove("show"),3200)}
  function setButton(b,l,label="Processando..."){if(!b)return;if(l){b.dataset.old=b.innerHTML;b.disabled=true;b.innerHTML=`<i class="fa-solid fa-spinner fa-spin"></i> ${html(label)}`}else{b.disabled=false;if(b.dataset.old){b.innerHTML=b.dataset.old;delete b.dataset.old}}}
  async function loadDeliveries(){const {data,error}=await db.rpc("go_burger_entregador_minhas_entregas_v1");if(error)throw error;state.deliveries=Array.isArray(data)?data:[];state.activeDriverId=state.deliveries[0]?.entregador_id||state.activeDriverId;$("#driverDeliveryCount").textContent=state.deliveries.length;const first=state.deliveries[0];if(first)$("#driverStore").textContent=first.loja_nome||"Go-burger";render()}
  function setAvailabilityUI(value){state.available=!!value;const b=$("#driverAvailability");if(!b)return;b.classList.toggle("online",state.available);b.setAttribute("aria-pressed",String(state.available));$("#driverAvailabilityText").textContent=state.available?"Online":"Offline";}
  async function toggleAvailability(){const b=$("#driverAvailability");setButton(b,true,"...");try{const next=!state.available;const {data,error}=await db.rpc("go_burger_entregador_definir_disponibilidade_v45",{p_disponivel:next});if(error)throw error;setAvailabilityUI(data?.disponivel??next);toast(next?"Você está online para receber ofertas.":"Você ficou offline.")}catch(e){toast(e.message||"Não foi possível alterar sua disponibilidade.")}finally{setButton(b,false)}}
  async function respondOffer(id,accept,b){let motivo=null;if(!accept)motivo=prompt("Se quiser, informe o motivo da recusa:")||null;setButton(b,true,accept?"Aceitando...":"Recusando...");try{const {error}=await db.rpc("go_burger_entregador_responder_oferta_v45",{p_pedido_id:Number(id),p_aceitar:accept,p_motivo:motivo});if(error)throw error;toast(accept?"Entrega aceita. Boa rota!":"Oferta recusada. A loja poderá chamar outro entregador.");await loadDeliveries()}catch(e){toast(e.message||"Não foi possível responder à oferta.")}finally{setButton(b,false)}}
  function render(){const w=$("#driverDeliveries");if(!w)return;if(!state.deliveries.length){w.innerHTML='<section class="driver-empty"><i class="fa-solid fa-circle-check"></i><h2>Nenhuma entrega atribuída</h2><p>Sua fila está livre neste momento.</p></section>';return}w.innerHTML=state.deliveries.map(d=>{const lat=Number(d.latitude),lng=Number(d.longitude),has=Number.isFinite(lat)&&Number.isFinite(lng),map=has?`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${lat},${lng}`)}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(d.endereco||"")}`;return `<article class="delivery-card ${d.status_entrega==="ofertada"?"offer":""}"><div class="delivery-card-head"><div><h3>Pedido #${html(d.numero_loja||d.pedido_id)}</h3><small>${html(d.loja_nome||"Go-burger")}</small></div><span class="delivery-status">${html(String(d.status_entrega||"atribuida").replaceAll("_"," "))}</span></div>${d.status_entrega==="ofertada"?`<div class="delivery-offer-banner"><i class="fa-solid fa-bell"></i> Nova oferta de entrega · aceite para liberar a rota</div>`:""}<div class="delivery-address"><strong>${html(d.cliente_nome||"Cliente")}</strong><br>${html(d.endereco||"Endereço não informado")}${d.bairro_nome?`<br>${html(d.bairro_nome)}`:""}</div><div class="delivery-line"><span>Contato</span><strong>${html(d.telefone||"—")}</strong></div><div class="delivery-line"><span>Pagamento</span><strong>${html(d.forma_pagamento||"—")} · ${html(d.pagamento_status||"—")}</strong></div><div class="delivery-line"><span>Total</span><strong>${money(d.total)}</strong></div><div class="delivery-line"><span>Distância</span><strong>${d.distancia_km!=null?`${Number(d.distancia_km).toFixed(1)} km`:"—"}</strong></div><div class="delivery-card-actions">${d.status_entrega==="ofertada"?`<button class="driver-btn success" data-offer="accept" data-pedido="${d.pedido_id}"><i class="fa-solid fa-check"></i> Aceitar</button><button class="driver-btn danger" data-offer="reject" data-pedido="${d.pedido_id}"><i class="fa-solid fa-xmark"></i> Recusar</button>`:`<a class="driver-btn primary" href="${map}" target="_blank" rel="noopener"><i class="fa-solid fa-route"></i>&nbsp; Abrir rota</a>`}${d.status_entrega==="atribuida"?`<button class="driver-btn secondary" data-delivery-status="coletada" data-pedido="${d.pedido_id}">Pedido coletado</button>`:""}${["atribuida","coletada"].includes(d.status_entrega)?`<button class="driver-btn secondary" data-delivery-status="em_rota" data-pedido="${d.pedido_id}">Sair para entrega</button>`:""}${["coletada","em_rota"].includes(d.status_entrega)?`<button class="driver-btn success" data-delivery-status="entregue" data-pedido="${d.pedido_id}">Confirmar entrega</button>`:""}</div></article>`}).join("")}
  async function updateStatus(id,status,b){setButton(b,true,"Atualizando...");try{const {error}=await db.rpc("go_burger_entregador_status_v1",{p_pedido_id:Number(id),p_status:status});if(error)throw error;toast("Entrega atualizada.");await loadDeliveries()}catch(e){toast(e.message||"Não foi possível atualizar.")}finally{setButton(b,false)}}

  function setLiveButton(active){const b=$("#driverLiveLocation");if(!b)return;b.classList.toggle("live",active);b.setAttribute("aria-pressed",String(active));b.innerHTML=active?'<span class="live-location-pulse"></span> Localização ao vivo':'<i class="fa-solid fa-satellite-dish"></i> Compartilhar em tempo real';}
  async function sendPosition(position,silent=false){
    if(!state.activeDriverId)throw new Error("Perfil de entregador não encontrado.");
    const {error}=await db.rpc("go_burger_atualizar_localizacao_entregador_v2",{p_entregador_id:Number(state.activeDriverId),p_latitude:Number(position.coords.latitude),p_longitude:Number(position.coords.longitude),p_precisao:Number(position.coords.accuracy||0),p_velocidade_mps:Number.isFinite(Number(position.coords.speed))?Number(position.coords.speed):null,p_direcao_graus:Number.isFinite(Number(position.coords.heading))?Number(position.coords.heading):null});if(error)throw error;
    $("#driverLocationText").textContent=`Atualizada ${new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})} · precisão aprox. ${Math.round(position.coords.accuracy||0)} m`;
    if(!silent)toast("Localização enviada.");
  }
  function toggleLiveLocation(){
    if(!navigator.geolocation)return toast("Geolocalização não disponível.");
    if(state.liveWatchId!==null){navigator.geolocation.clearWatch(state.liveWatchId);state.liveWatchId=null;setLiveButton(false);toast("Compartilhamento em tempo real pausado.");return;}
    state.liveWatchId=navigator.geolocation.watchPosition(pos=>sendPosition(pos,true).catch(e=>toast(e.message)),()=>{toast("Não foi possível acompanhar sua localização.");toggleLiveLocation();},{enableHighAccuracy:true,maximumAge:8000,timeout:12000});
    setLiveButton(true);toast("Localização em tempo real ativada.");
  }

  async function sendLocation(){if(!navigator.geolocation)return toast("Geolocalização não disponível.");const b=$("#driverSendLocation");setButton(b,true,"Localizando...");navigator.geolocation.getCurrentPosition(async p=>{try{if(!state.activeDriverId){const {data,error}=await db.from("entregadores").select("id").eq("user_id",state.user.id).eq("ativo",true).limit(1);if(error)throw error;state.activeDriverId=data?.[0]?.id||null}if(!state.activeDriverId)throw new Error("Perfil não encontrado.");const {error}=await db.rpc("go_burger_atualizar_localizacao_entregador_v2",{p_entregador_id:Number(state.activeDriverId),p_latitude:Number(p.coords.latitude),p_longitude:Number(p.coords.longitude),p_precisao:Number(p.coords.accuracy||0),p_velocidade_mps:Number.isFinite(Number(p.coords.speed))?Number(p.coords.speed):null,p_direcao_graus:Number.isFinite(Number(p.coords.heading))?Number(p.coords.heading):null});if(error)throw error;$("#driverLocationText").textContent=`Atualizada agora · precisão aprox. ${Math.round(p.coords.accuracy||0)} m`;toast("Localização enviada.")}catch(e){toast(e.message||"Falha ao enviar localização.")}finally{setButton(b,false)}},()=>{toast("Permissão de localização não concedida.");setButton(b,false)},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
  $("#driverRefresh")?.addEventListener("click",async e=>{setButton(e.currentTarget,true,"Atualizando...");try{await loadDeliveries()}catch(x){toast(x.message)}finally{setButton(e.currentTarget,false)}});$("#driverSendLocation")?.addEventListener("click",sendLocation);$("#driverLiveLocation")?.addEventListener("click",toggleLiveLocation);$("#driverAvailability")?.addEventListener("click",toggleAvailability);$("#driverHome")?.addEventListener("click",()=>location.href="../burger/index.html");
  document.addEventListener("click",e=>{const offer=e.target.closest?.("[data-offer]");if(offer){respondOffer(offer.dataset.pedido,offer.dataset.offer==="accept",offer);return}const b=e.target.closest?.("[data-delivery-status]");if(b)updateStatus(b.dataset.pedido,b.dataset.deliveryStatus,b)});
  try{const {data,error}=await db.auth.getSession();if(error)throw error;state.user=data?.session?.user||null;if(!state.user){$("#driverName").textContent="Faça login";$("#driverNoAccess")?.classList.remove("hidden");return}const {data:drivers,error:de}=await db.from("entregadores").select("id,nome,loja_id,disponivel,onboarding_status").eq("user_id",state.user.id).eq("ativo",true).limit(10);if(de)throw de;const d=drivers?.[0];if(!d){$("#driverName").textContent="Sem vínculo ativo";try{const {data:app}=await db.rpc("go_burger_entregador_minha_solicitacao_v45");state.application=app||null;const title=$("#driverNoAccessTitle"),text=$("#driverNoAccessText");if(app?.status==="aprovada"){title.textContent="Perfil aprovado, aguardando hamburgueria";text.textContent="Seu cadastro foi aprovado. Aceite um convite de uma hamburgueria para começar a receber entregas."}else if(app?.status){title.textContent=`Cadastro ${String(app.status).replaceAll("_"," ")}`;text.textContent=app.observacao_analise||"Acompanhe ou atualize seu cadastro na área de entregadores."}}catch{}$("#driverNoAccess")?.classList.remove("hidden");return}state.activeDriverId=d.id;setAvailabilityUI(drivers.some(x=>x.disponivel));$("#driverName").textContent=d.nome||state.user.email||"Entregador";await loadDeliveries();setInterval(()=>loadDeliveries().catch(()=>{}),20000)}catch(e){console.error(e);toast(e.message||"Não foi possível abrir o painel.")}
});
