"use strict";
(() => {
  const SUPABASE_URL="https://ethlgaszdextwckdwgsf.supabase.co",KEY="sb_publishable_qEhxWcCbekPjYFUW-EQ1ow_xccHG8aJ";
  const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const COMMERCIAL_GROWTH_ENABLED=false,REFERRAL_REWARDS_ENABLED=false;
  let db,sponsored=[],timer;
  function sessionKey(){let k=localStorage.getItem("go_burger_ad_session");if(!k){k=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem("go_burger_ad_session",k)}return k}
  function captureRef(){if(!REFERRAL_REWARDS_ENABLED)return;const r=new URL(location.href).searchParams.get("ref");if(r)localStorage.setItem("go_burger_pending_ref",r.trim().toUpperCase())}
  async function tryReferral(){if(!REFERRAL_REWARDS_ENABLED)return;const s=await db.auth.getSession();if(!s.data.session?.user)return;const code=localStorage.getItem("go_burger_pending_ref");if(!code)return;const r=await db.rpc("go_burger_registrar_indicacao_v1",{p_codigo:code});if(!r.error)localStorage.removeItem("go_burger_pending_ref")}
  async function load(){if(!COMMERCIAL_GROWTH_ENABLED){sponsored=[];render();return;}const category=document.querySelector("#marketCategories .active")?.dataset?.category||null;const r=await db.rpc("go_burger_marketplace_patrocinados_v1",{p_posicionamento:"marketplace_destaque",p_categoria:category,p_limit:10});if(r.error)return console.warn("Patrocinados",r.error.message);sponsored=r.data||[];render()}
  function render(){const section=$("#sponsoredSection"),wrap=$("#sponsoredStores");if(!section||!wrap)return;section.classList.toggle("hidden",!sponsored.length);wrap.innerHTML=sponsored.map(s=>`<article class="gb-sponsored-pro" data-store="${esc(s.slug)}" data-sponsored-id="${s.patrocinio_id}"><span class="gb-sponsored-badge"><i class="fa-solid fa-bolt"></i>${esc(s.selo||'Patrocinado')}</span><h3>${esc(s.titulo_patrocinio||s.nome)}</h3><p>${esc(s.chamada||s.slogan||s.descricao||'Parceiro em destaque na Go-burger.')}</p><span class="gb-sponsored-location"><i class="fa-solid fa-location-dot"></i> ${esc([s.cidade,s.estado].filter(Boolean).join(' · '))}</span><button class="store-open-btn" data-store-open="${esc(s.slug)}" data-sponsored-id="${s.patrocinio_id}" type="button">Ver hamburgueria <i class="fa-solid fa-arrow-right"></i></button></article>`).join("");sponsored.forEach(s=>db.rpc("go_burger_patrocinio_evento_v1",{p_patrocinio_id:s.patrocinio_id,p_evento:"impressao",p_session_key:sessionKey()}).catch(()=>{}))}
  function schedule(){clearTimeout(timer);timer=setTimeout(load,500)}
  document.addEventListener("DOMContentLoaded",()=>{if(!window.supabase?.createClient)return;db=window.supabase.createClient(SUPABASE_URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,storageKey:"go-burger-auth-v1"}});captureRef();setTimeout(()=>{load();tryReferral()},1000);["marketSearch","cityFilter","sortFilter","openOnly"].forEach(id=>$("#"+id)?.addEventListener("input",schedule));$("#marketCategories")?.addEventListener("click",schedule);document.addEventListener("click",e=>{const x=e.target.closest?.("[data-sponsored-id]");if(x&&COMMERCIAL_GROWTH_ENABLED)db.rpc("go_burger_patrocinio_evento_v1",{p_patrocinio_id:Number(x.dataset.sponsoredId),p_evento:"clique",p_session_key:sessionKey()}).catch(()=>{})},true);db.auth.onAuthStateChange(()=>setTimeout(tryReferral,300))});
})();
